apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wp-svc-clusterip
  namespace: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wp-deploy
  clusterIP: None