apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2wp-pvc-rwx
  namespace: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi