apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc-rwx
  namespace: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi