apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wp-dpm
  namespace: wordpress
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wp-cm-vars
              key: wp_db_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-connection
              key: wp_db_password
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-cm-vars
              key: wp_db_host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wp-cm-vars
              key: wp_db_name
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-pers-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-pers-storage
        persistentVolumeClaim:
          claimName: wp-pvc-rwx 